server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:smartcourier_auth}?createDatabaseIfNotExist=true&useSSL=${DB_USE_SSL:false}&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    template:
      observation-enabled: true
    listener:
      simple:
        observation-enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

security:
  jwt:
    secret: ${JWT_SECRET:SmartCourierSecretKeyForJwtTokenGeneration123456}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    enabled: ${TRACING_ENABLED:true}
    sampling:
      probability: ${TRACING_SAMPLE_PROBABILITY:1.0}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}
      connect-timeout: 1s
      read-timeout: 10s
  endpoints:
    web:
      exposure:
        include: health,info,metrics
